# TODO: Ask George for NPM permissions to create token


# name: Publish to NPM

# on:
#   push:
#     branches: [ main ]
#     paths-ignore:
#       - 'docs/**'
#       - '*.md'
#       - '.github/**'

# jobs:
#   publish:
#     runs-on: ubuntu-latest
    
#     # Only run if tests pass
#     needs: []
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4
      
#     - name: Setup Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: 'lts/*'
#         cache: 'npm'
#         registry-url: 'https://registry.npmjs.org'
        
#     - name: Install dependencies
#       run: npm ci
      
#     - name: Run tests
#       run: npm run test:run
      
#     - name: Build package
#       run: npm run build
      
#     - name: Check if version changed
#       id: version-check
#       run: |
#         CURRENT_VERSION=$(node -p "require('./package.json').version")
#         PUBLISHED_VERSION=$(npm view @levante-framework/permissions-core version 2>/dev/null || echo "0.0.0")
#         echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
#         echo "published-version=$PUBLISHED_VERSION" >> $GITHUB_OUTPUT
#         if [ "$CURRENT_VERSION" != "$PUBLISHED_VERSION" ]; then
#           echo "version-changed=true" >> $GITHUB_OUTPUT
#           echo "Version changed from $PUBLISHED_VERSION to $CURRENT_VERSION"
#         else
#           echo "version-changed=false" >> $GITHUB_OUTPUT
#           echo "Version unchanged: $CURRENT_VERSION"
#         fi
        
#     - name: Publish to NPM
#       if: steps.version-check.outputs.version-changed == 'true'
#       run: npm publish --access public
#       env:
#         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
#     - name: Create GitHub Release
#       if: steps.version-check.outputs.version-changed == 'true'
#       uses: actions/create-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         tag_name: v${{ steps.version-check.outputs.current-version }}
#         release_name: Release v${{ steps.version-check.outputs.current-version }}
#         body: |
#           ## Changes
          
#           See the [CHANGELOG](./CHANGELOG.md) for details.
          
#           ## Installation
          
#           ```bash
#           npm install @levante-framework/permissions-core@${{ steps.version-check.outputs.current-version }}
#           ```
#         draft: false
#         prerelease: false
